import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Layout from "./layout";

export default function Home() {
  return (
    <div className={styles.container}>
      <Layout>
        <Head>
          <title>My first blog next app</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <nav> </nav>
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Welcome to my first blog next app !</h1>
          <br />
          <br />
          <ul>
            <li>
              <Link href="/blog/first-article">First-article</Link>
            </li>
            <li>
              <Link href="/blog/second-article">Second-article</Link>
            </li>
          </ul>

          <p className={styles.description}>
            Hello, je suis Kevin ! Si tu es ici ça signifie que tu aimes bien
            venir regarder des sites en constructions fait par des développeurs
            en apprentissage. Bravo, tu es courageux ! Maintenant que tu es là
            et que tu as deviné ce que je faisais va visiter :)
            <code className={styles.code}></code>
          </p>
        </main>

        <footer className={styles.footer}>
          <a target="_blank" rel="noopener noreferrer">
            Powered by{" Kevin"}
            <span className={styles.logo}></span>
          </a>
        </footer>
      </Layout>
    </div>
  );
}
